🚀 Feat : 게시글 페이지 마크업 - (업데이트 예정) #9
prgrms-web-devcourse-final-project/WEB1_2_FlowDay_FE pull request #17
Opened 2024-11-28 08:10 UTC by JaeHyun10-03

## 🔓closed #issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
![게시글 페이지 움짤](https://github.com/user-attachments/assets/a881ce62-12c5-4a6c-8936-9e2fea304232)

## 📌 과제 설명 
- 상단 헤더 교체
- 검색창 & 카테고리 버튼 마크업 구현
- 포스트 아이템 마크업 구현

## 👩‍💻 요구 사항과 구현 내용 
- 
-
-

## ✅ 피드백 반영사항  
-
-
-

## ✋ PR 포인트 & 궁금한 점 
- 검색창 기능 구현 - API 구현 시 업데이트 예정
- 카테고리 - API 구현 시 서버로 데이터 전송 기능 업데이트 예정
- 포스트 아이템 - API 구현 시 좋아요, 댓글 수 업데이트 예정
- 무한스크롤 - API 구현 시 10개씩 데이터를 받아올 수 있도록 업데이트 예정

2024-11-28 08:44 UTC, hyejun-fe submitted a review, later dismissed
고생하셨습니다!

2024-11-28 08:56 UTC, snsdl0905 requested changes
고생하셨습니다!!🙇‍♀️ 아래 부분들 수정해주시면 좋을 것 같아요ㅎㅎ

- interface IPost는 따로 파일로 분리하면 좋을 것 같습니다.
- 피드백 받은대로 lint 부분은 prettier로 바꿔주시면 좋을 것 같습니다.
- 주석도 제거해주세요.

2024-11-28 15:52 UTC, JaeHyun10-03 commented
> 고생하셨습니다!!🙇‍♀️ 아래 부분들 수정해주시면 좋을 것 같아요ㅎㅎ
> 
> * interface IPost는 따로 파일로 분리하면 좋을 것 같습니다.
> * 피드백 받은대로 lint 부분은 prettier로 바꿔주시면 좋을 것 같습니다.
> * 주석도 제거해주세요.

interface를 제외하고 모두 수정했습니다. IPost는 해당 파일에서만 고유하게 사용하는 인터페이스로서 다른 파일로 분리하는 것이 더 좋지 않다고 생각하였습니다. 추가적으로 질문 사항 있으시면 말씀 부탁드립니다 :)

2024-11-29 05:02 UTC, snsdl0905 approved these changes

2024-11-29 05:11 UTC, snsdl0905 reviewed
고생하셨습니다 !

2024-11-29 05:11 UTC, merged

2024-12-05 11:25 UTC, Seung-wan commented on .prettierrc.js
> +  printWidth: 200,
보통은 최대 120정도로 설정하는 것 같기는 합니다!
모든 사람이 큰 모니터를 사용하는 것이 아니라서 가로로 너무 길어지면 그것도 보기 어렵긴 하니까요!

2024-12-05 11:25 UTC, Seung-wan commented on src/assets/icons/back.png
일반적으로 아이콘은 png가 아닌 svg 확장자로 다루는 편인데요!
요 차이점을 한번 찾아보시면 좋을 것 같습니다!

2024-12-05 11:25 UTC, Seung-wan commented on App.tsx
>  `;
상수나, 스타일 코드를 컴포넌트의 위쪽에 작성하는 경우도 있고 아래쪽에 작성하는 경우도 있어서 일관되게 사용해주시면 좋을 것 같네요!

2024-12-05 11:25 UTC, Seung-wan commented on App.tsx
> +  }, []);
`const isFontsLoaded = useLoadFonts();` 요런식으로 사용할 수 있게끔 커스텀 훅으로 다뤄주시면 훨씬 괜찮을 것 같네요!

2024-12-05 11:25 UTC, Seung-wan commented on App.tsx
> +  };
이 부분은 컴포넌트 외부에 작성해주세요~

2024-12-05 11:25 UTC, Seung-wan commented on App.tsx
> +  );
저는 Tab이랑 Stack 내비게이션 관리해주시고 있는 부분은 지금도 전혀 문제는 없는 것 같아요.
코드를 작성하다보면 필요해서 길어지는 부분은 마땅히 그래도 상관이 없는데 저는 지금이 그런 상황이라고 생각하긴 합니다!
다만 조금 더 깔끔하게 표현해보고자 한다면 Tab쪽의 JSX를 map을 돌려서 표현하기 위해 필요한 데이터들을 객체 배열로 추상화해볼 수 있을 것 같네요!

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostCategoryButton.tsx
> +    </CategoryButton>
이미지는 import로 표현해줄 수는 없을까요~?
```ts
import icon from './my-icon.png';
<Image source={icon} />
```

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostCategoryButton.tsx
> +  onPress: () => void; // onPress 이벤트를 props로 받도록 인터페이스 추가
요런 주석은 필요 없을 것 같아요~

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostCategoryModal.tsx
> +const PostCategoryModal: React.FC<PostCategoryModalProps> = ({ onPress }) => {
이제는 React.FC와 같은 타입은 잘 사용하지 않는 편입니다~ 함수의 매개변수에 직접 타입을 정의해주는 편이에요.

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostCategoryModal.tsx
> +  ];
요런 값들은 모두 컴포넌트 외부로 분리해주세요~
그리고 변수명도 상수 컨벤션에 맞게 작성되면 좋을 것 같네요!

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostCategoryModal.tsx
> +              >
key값을 index가 아닌 유니크한 값으로 표현할 수 있을때는 유니크한 값을 사용해주세요~

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostItem.tsx
> +  const [year, month, day] = postData.createdAt.split('T')[0].split('-');
날짜를 다룰때는 날짜 라이브러리를 사용해서 훨씬 명확하게 다뤄주시면 좋을 것 같습니다~

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostItem.tsx
> +            <InfoIcon source={require('../../assets/icons/like.png')} />
요런 이슈가 있었네요! 요건 적어주신대로 해결되면 좋을 것 같네요!

2024-12-05 11:25 UTC, Seung-wan commented on src/components/post/PostSearch.tsx
> +  const [input, setInput] = useState('');
이 값은 Props로 받도록 해야하지 않을까요? 입력값을 결국 사용하는 쪽은 외부가 될테니까요!

2024-12-05 11:25 UTC, Seung-wan commented on src/pages/post-list-page/PostListPage.tsx
> +  const [onCategoryModal, isOnCategoryModal] = useState(false);
상태명 확인해주세요~

2024-12-05 11:25 UTC, Seung-wan commented on src/pages/post-list-page/PostListPage.tsx
> +    {
요런 값들은 임시로 작성된 값이라고 해도 무조건 컴포넌트 외부에 작성해주세요

2024-12-05 11:25 UTC, Seung-wan commented on src/pages/post-list-page/PostListPage.tsx
> +          setIsLatest(!isLatest);
기존 상태를 이용해서 새로운 상태값을 만들어낼때는 updater function을 이용해서 업데이트하는게 좋습니다~